### ISSUE TITLE
unresolved dependency: com.mediamath.play#play-dynamodb_2.11;0.4.1: not found

### ISSUE THREAD

**Issue by aloon** [MediaMath/play-dynamodb#3]
sbt fails when try to resolv the dependency

```
 Error:Error while importing SBT project:
...
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: com.mediamath.play#play-dynamodb_2.11;0.4.1: not found
[error] Use 'last' for the full log.

See complete log in ~/Library/Logs/IdeaIC14/sbt.last.log
```

**Comment by alekseyig** [comment]
Hi,

Did you get this error when you try to build the artifact or when you try to use it? If latter, then you need to publish the built artifact first, for example 'sbt publishLocal' and try to use it.

**Comment by aloon** [comment]
when I try to use it
do you resolv the dependency?

**Comment by alekseyig** [comment]
please build and publish (most likely locally) this lib before you use it.
